
package pruebaconectbd;

import java.awt.AlphaComposite;
import java.awt.Color;
import java.awt.event.*;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.IntStream;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Luis
 */
public class FrameJuegos extends javax.swing.JFrame {

    accesobd base = new accesobd("localhost", "root", "12345678", "tiendavideojuegos");
    private ArrayList<Detalle> detallesSeleccionados = new ArrayList<>();
    Juego juego;
    int idprod;
    CasaDesarrolladora casa;
    Juego_Distribuidora juegoDist;
    Distribuidor distribuidor;
    Detalle detalle;
    Cliente cliente;
    Venta venta;
    Detalle_Venta detVenta;
    private int id_juego;
    private int id_distribuidor;
    private int id_juegodistribuidor;
    private int id_casadesarrolladora;
    private int id_venta;
    private JTextField obtenerCampo;
    DefaultTableModel modeloTabla;

    /**
     * Creates new form FrameJuegos
     *
     * @throws java.lang.Exception
     */
    public FrameJuegos() throws Exception {
        initComponents();
        base.conectaBD();
        juego = new Juego(base);
        casa = new CasaDesarrolladora(base);
        distribuidor = new Distribuidor(base);
        juegoDist = new Juego_Distribuidora(base);
        cliente = new Cliente(base);
        venta = new Venta(base);
        detVenta = new Detalle_Venta(base);
        sumaSubtotal(InputTotal);
        Rellenar_Casa(CasaComboBox);
        Rellenar_Distribuidor(DistribuidoraComboBox);
        Rellenar_videoJuegos(VjComboBox);
        mostrar(TableJuego, "SELECT JUEGO.ID_JUEGO AS ID, JUEGO.TITULO AS NOMBRE, JUEGO.GENERO, JUEGO.PRECIO, JUEGO.STOCK, CASA_DESARROLLADORA.NOMBRE AS DESARROLLADORA, JUEGO_DISTRIBUIDORA.PUBLICACION, DISTRIBUIDORA.NOMBRE AS DISTRIBUIDORA\n"
                + "FROM CASA_DESARROLLADORA INNER JOIN (JUEGO INNER JOIN (JUEGO_DISTRIBUIDORA INNER JOIN DISTRIBUIDORA ON DISTRIBUIDORA.ID_DISTRIBUIDORA = JUEGO_DISTRIBUIDORA.ID_DISTRIBUIDORA)\n"
                + "ON JUEGO_DISTRIBUIDORA.ID_JUEGO = JUEGO.ID_JUEGO) ON JUEGO.ID_CASADESARROLLADORA = CASA_DESARROLLADORA.ID_CASADESARROLLADORA;;");
        MisMetodos();
        anadirFecha();
    }

    private void anadirFecha() {
        Calendar cal = Calendar.getInstance();
        FechaVenta.setDate(cal.getTime());
        //FechaVenta.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelPadre = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        JRegistroJuegos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableJuego = new javax.swing.JTable();
        txtTitulo = new javax.swing.JTextField();
        txtGenero = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        BtnNuevo = new javax.swing.JButton();
        BtnActualizar = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        Agregar = new javax.swing.JButton();
        dateLanzamiento = new com.toedter.calendar.JDateChooser();
        Nombre_CasaD = new javax.swing.JTextField();
        Pais_CasaD = new javax.swing.JTextField();
        Telefono_CasaD = new javax.swing.JTextField();
        videojuegoSeparador = new javax.swing.JSeparator();
        SeparadorJuego = new javax.swing.JSeparator();
        Nombre_Distribuidor = new javax.swing.JTextField();
        Pais_Distribuidor = new javax.swing.JTextField();
        Correo_Distribuidor = new javax.swing.JTextField();
        videojuegoSeparador1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        CasaComboBox = new javax.swing.JComboBox<>();
        DistribuidoraComboBox = new javax.swing.JComboBox<>();
        jRegistroVenta = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        videojuegoSeparador2 = new javax.swing.JSeparator();
        Cedula = new javax.swing.JTextField();
        Nombre_CL = new javax.swing.JTextField();
        Apellido_CL = new javax.swing.JTextField();
        InputBuscarCL = new javax.swing.JTextField();
        BuscarCL = new javax.swing.JButton();
        Telefono = new javax.swing.JTextField();
        Direccion = new javax.swing.JTextField();
        Correo_CL = new javax.swing.JTextField();
        videojuegoSeparador3 = new javax.swing.JSeparator();
        FechaVenta = new com.toedter.calendar.JDateChooser();
        VjComboBox = new javax.swing.JComboBox<>();
        InputCantidad = new javax.swing.JTextField();
        actualizarCantidad = new javax.swing.JButton();
        EliminarProducto = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableVideo = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        InputTotal = new javax.swing.JTextField();
        GuarVenta = new javax.swing.JButton();
        VaciarVenta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventas de VideoJuegos");
        setResizable(false);

        JPanelPadre.setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane2.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane2MouseClicked(evt);
            }
        });

        JRegistroJuegos.setBackground(new java.awt.Color(255, 255, 255));
        JRegistroJuegos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JRegistroJuegosMouseClicked(evt);
            }
        });

        TableJuego.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Titulo", "Genero", "Plataforma", "Precio", "Stock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableJuego.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableJuegoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableJuego);

        txtTitulo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(203, 203, 203)), "Nombre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 13))); // NOI18N
        txtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloActionPerformed(evt);
            }
        });

        txtGenero.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(203, 203, 203)), "Genero", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 13))); // NOI18N
        txtGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGeneroActionPerformed(evt);
            }
        });

        txtStock.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(203, 203, 203)), "Cantidad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 13))); // NOI18N
        txtStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStockActionPerformed(evt);
            }
        });

        txtPrecio.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(203, 203, 203)), "Precio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 13))); // NOI18N
        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });

        BtnNuevo.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        BtnNuevo.setText("Nuevo");
        BtnNuevo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNuevoActionPerformed(evt);
            }
        });

        BtnActualizar.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        BtnActualizar.setText("Actualizar");
        BtnActualizar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnActualizarActionPerformed(evt);
            }
        });

        BtnEliminar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        BtnEliminar.setForeground(new java.awt.Color(255, 0, 0));
        BtnEliminar.setText("Eliminar");
        BtnEliminar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        Agregar.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        Agregar.setText("Enviar");
        Agregar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });

        dateLanzamiento.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(203, 203, 203)), "Fecha Publicación", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 13))); // NOI18N
        dateLanzamiento.setDateFormatString("yyyy-MM-dd");

        Nombre_CasaD.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(203, 203, 203)), "Nombre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 13))); // NOI18N

        Pais_CasaD.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(203, 203, 203)), "País", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 13))); // NOI18N

        Telefono_CasaD.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(203, 203, 203)), "Teléfono", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 13))); // NOI18N

        videojuegoSeparador.setForeground(new java.awt.Color(255, 255, 255));
        videojuegoSeparador.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 0, 0, new java.awt.Color(203, 203, 203)), "Casa Desarrolladora", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 14))); // NOI18N

        SeparadorJuego.setForeground(new java.awt.Color(255, 255, 255));
        SeparadorJuego.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 0, 0, new java.awt.Color(203, 203, 203)), "Videojuego", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 14))); // NOI18N

        Nombre_Distribuidor.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(203, 203, 203)), "Nombre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 13))); // NOI18N

        Pais_Distribuidor.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(203, 203, 203)), "País", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 13))); // NOI18N

        Correo_Distribuidor.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(203, 203, 203)), "Correo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 13))); // NOI18N

        videojuegoSeparador1.setForeground(new java.awt.Color(255, 255, 255));
        videojuegoSeparador1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 0, 0, new java.awt.Color(203, 203, 203)), "Distribuidor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 3, 15)); // NOI18N
        jLabel1.setText("Registros");

        CasaComboBox.setFont(new java.awt.Font("Trebuchet MS", 2, 11)); // NOI18N
        CasaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----- Seleccionar ------", "------- Agregar -------" }));
        CasaComboBox.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(203, 203, 203)), "Casas Desarrolladoras", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 13))); // NOI18N
        CasaComboBox.setRequestFocusEnabled(false);
        CasaComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CasaComboBoxItemStateChanged(evt);
            }
        });

        DistribuidoraComboBox.setFont(new java.awt.Font("Trebuchet MS", 2, 11)); // NOI18N
        DistribuidoraComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---- Seleccionar ----", "------ Agregar ------" }));
        DistribuidoraComboBox.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(203, 203, 203)), "Distribuidoras", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 2, 13))); // NOI18N
        DistribuidoraComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                DistribuidoraComboBoxItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout JRegistroJuegosLayout = new javax.swing.GroupLayout(JRegistroJuegos);
        JRegistroJuegos.setLayout(JRegistroJuegosLayout);
        JRegistroJuegosLayout.setHorizontalGroup(
            JRegistroJuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JRegistroJuegosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JRegistroJuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JRegistroJuegosLayout.createSequentialGroup()
                        .addGroup(JRegistroJuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(JRegistroJuegosLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(JRegistroJuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(JRegistroJuegosLayout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addComponent(BtnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Agregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(37, 37, 37)
                                        .addComponent(BtnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(31, 31, 31)
                                        .addComponent(BtnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(97, 97, 97))
                                    .addGroup(JRegistroJuegosLayout.createSequentialGroup()
                                        .addGroup(JRegistroJuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(JRegistroJuegosLayout.createSequentialGroup()
                                                .addComponent(dateLanzamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(20, 20, 20)
                                                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(20, 20, 20)
                                                .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(JRegistroJuegosLayout.createSequentialGroup()
                                                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(57, 57, 57)
                                                .addComponent(txtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(JRegistroJuegosLayout.createSequentialGroup()
                                                .addGroup(JRegistroJuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(Pais_CasaD, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                                                    .addComponent(CasaComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(57, 57, 57)
                                                .addGroup(JRegistroJuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(Telefono_CasaD, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                                                    .addComponent(Nombre_CasaD)))
                                            .addGroup(JRegistroJuegosLayout.createSequentialGroup()
                                                .addGroup(JRegistroJuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(Pais_Distribuidor, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                                                    .addComponent(DistribuidoraComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(57, 57, 57)
                                                .addGroup(JRegistroJuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(Nombre_Distribuidor, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(Correo_Distribuidor, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(18, 18, 18)))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JRegistroJuegosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(JRegistroJuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SeparadorJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 838, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(JRegistroJuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(videojuegoSeparador1, javax.swing.GroupLayout.PREFERRED_SIZE, 836, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(videojuegoSeparador, javax.swing.GroupLayout.PREFERRED_SIZE, 836, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(JRegistroJuegosLayout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(23, 23, 23))))
        );
        JRegistroJuegosLayout.setVerticalGroup(
            JRegistroJuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JRegistroJuegosLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(JRegistroJuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(videojuegoSeparador, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JRegistroJuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre_CasaD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CasaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JRegistroJuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pais_CasaD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Telefono_CasaD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(SeparadorJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(JRegistroJuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(JRegistroJuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JRegistroJuegosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(JRegistroJuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(JRegistroJuegosLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(dateLanzamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addComponent(videojuegoSeparador1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(JRegistroJuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre_Distribuidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DistribuidoraComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JRegistroJuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Correo_Distribuidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pais_Distribuidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(JRegistroJuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnNuevo)
                    .addComponent(Agregar)
                    .addComponent(BtnActualizar)
                    .addComponent(BtnEliminar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jTabbedPane2.addTab("Juegos", JRegistroJuegos);

        jRegistroVenta.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 3, 15)); // NOI18N
        jLabel2.setText("Registros de Ventas");

        videojuegoSeparador2.setForeground(new java.awt.Color(255, 255, 255));
        videojuegoSeparador2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 0, 0, new java.awt.Color(203, 203, 203)), "Información de Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 14))); // NOI18N

        Cedula.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(203, 203, 203)), "Cédula", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 13))); // NOI18N

        Nombre_CL.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(203, 203, 203)), "Nombre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 13))); // NOI18N

        Apellido_CL.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(203, 203, 203)), "Apellido", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 13))); // NOI18N

        InputBuscarCL.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(203, 203, 203)), "Buscar Cédula", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 12))); // NOI18N

        BuscarCL.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        BuscarCL.setText("Buscar");

        Telefono.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(203, 203, 203)), "Teléfono", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 13))); // NOI18N

        Direccion.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(203, 203, 203)), "Dirección", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 13))); // NOI18N

        Correo_CL.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(203, 203, 203)), "Correo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 13))); // NOI18N

        videojuegoSeparador3.setForeground(new java.awt.Color(255, 255, 255));
        videojuegoSeparador3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 0, 0, new java.awt.Color(203, 203, 203)), "Información de la Venta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 14))); // NOI18N

        FechaVenta.setBackground(new java.awt.Color(255, 255, 255));
        FechaVenta.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(203, 203, 203)), "Fecha Venta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 13))); // NOI18N
        FechaVenta.setDateFormatString("yyyy-MM-dd");

        VjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        VjComboBox.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(203, 203, 203)), "VideoJuegos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 13))); // NOI18N
        VjComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                VjComboBoxItemStateChanged(evt);
            }
        });

        InputCantidad.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(203, 203, 203)), "Cantidad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 13))); // NOI18N

        actualizarCantidad.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        actualizarCantidad.setText("Actualizar");
        actualizarCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarCantidadActionPerformed(evt);
            }
        });

        EliminarProducto.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        EliminarProducto.setText("Eliminar");
        EliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarProductoActionPerformed(evt);
            }
        });

        jTableVideo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Producto", "Precio", "Cantidad", "Sub-Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableVideo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableVideoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableVideo);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel3.setText("TOTAL:");

        InputTotal.setEditable(false);
        InputTotal.setFont(new java.awt.Font("Trebuchet MS", 2, 18)); // NOI18N
        InputTotal.setText("132");
        InputTotal.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        InputTotal.setFocusable(false);

        GuarVenta.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        GuarVenta.setText("Guardar");
        GuarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuarVentaActionPerformed(evt);
            }
        });

        VaciarVenta.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        VaciarVenta.setText("Vaciar");

        javax.swing.GroupLayout jRegistroVentaLayout = new javax.swing.GroupLayout(jRegistroVenta);
        jRegistroVenta.setLayout(jRegistroVentaLayout);
        jRegistroVentaLayout.setHorizontalGroup(
            jRegistroVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jRegistroVentaLayout.createSequentialGroup()
                .addGroup(jRegistroVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jRegistroVentaLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jRegistroVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(videojuegoSeparador2, javax.swing.GroupLayout.PREFERRED_SIZE, 836, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(videojuegoSeparador3, javax.swing.GroupLayout.PREFERRED_SIZE, 836, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jRegistroVentaLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jRegistroVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(InputCantidad)
                                    .addComponent(FechaVenta, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE))
                                .addGap(57, 57, 57)
                                .addGroup(jRegistroVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(VjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jRegistroVentaLayout.createSequentialGroup()
                                        .addComponent(actualizarCantidad)
                                        .addGap(42, 42, 42)
                                        .addComponent(EliminarProducto))))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jRegistroVentaLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(InputTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(GuarVenta)
                                .addGap(62, 62, 62)
                                .addComponent(VaciarVenta)
                                .addGap(108, 108, 108))))
                    .addGroup(jRegistroVentaLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jRegistroVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jRegistroVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nombre_CL, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jRegistroVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Correo_CL, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Apellido_CL, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jRegistroVentaLayout.createSequentialGroup()
                                .addComponent(InputBuscarCL, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BuscarCL)))))
                .addGap(15, 15, 15))
        );
        jRegistroVentaLayout.setVerticalGroup(
            jRegistroVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jRegistroVentaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addGroup(jRegistroVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jRegistroVentaLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(videojuegoSeparador2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(InputBuscarCL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(jRegistroVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nombre_CL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Apellido_CL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jRegistroVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Correo_CL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jRegistroVentaLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(BuscarCL)))
                .addGap(37, 37, 37)
                .addComponent(videojuegoSeparador3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jRegistroVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FechaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jRegistroVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jRegistroVentaLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jRegistroVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EliminarProducto)
                            .addComponent(actualizarCantidad)))
                    .addComponent(InputCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jRegistroVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(InputTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GuarVenta)
                    .addComponent(VaciarVenta))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Ventas", jRegistroVenta);

        javax.swing.GroupLayout JPanelPadreLayout = new javax.swing.GroupLayout(JPanelPadre);
        JPanelPadre.setLayout(JPanelPadreLayout);
        JPanelPadreLayout.setHorizontalGroup(
            JPanelPadreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelPadreLayout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        JPanelPadreLayout.setVerticalGroup(
            JPanelPadreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelPadreLayout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPanelPadre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPanelPadre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNuevoActionPerformed
        nuevo();
    }//GEN-LAST:event_BtnNuevoActionPerformed

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
        txtGenero.grabFocus();
    }//GEN-LAST:event_txtTituloActionPerformed

    private void txtGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGeneroActionPerformed
        //txtPlataforma.grabFocus();
        dateLanzamiento.grabFocus();
    }//GEN-LAST:event_txtGeneroActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        txtStock.grabFocus();
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void txtStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockActionPerformed
        if (!"".equals(txtTitulo.getText())
                && !"".equals(txtGenero.getText())
                && !"".equals(dateLanzamiento.getDate())
                && !"".equals(txtPrecio.getText())
                && !"".equals(txtStock.getText())) {
            enviar();
            nuevo();
            txtTitulo.grabFocus();
        }
    }//GEN-LAST:event_txtStockActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        eliminaRegistro();
        nuevo();
        mostrar(TableJuego, "SELECT JUEGO.ID_JUEGO AS ID, JUEGO.TITULO AS NOMBRE, JUEGO.GENERO, JUEGO.PRECIO, JUEGO.STOCK, CASA_DESARROLLADORA.NOMBRE AS DESARROLLADORA, JUEGO_DISTRIBUIDORA.PUBLICACION, DISTRIBUIDORA.NOMBRE AS DISTRIBUIDORA\n"
                + "FROM CASA_DESARROLLADORA INNER JOIN (JUEGO INNER JOIN (JUEGO_DISTRIBUIDORA INNER JOIN DISTRIBUIDORA ON DISTRIBUIDORA.ID_DISTRIBUIDORA = JUEGO_DISTRIBUIDORA.ID_DISTRIBUIDORA)\n"
                + "ON JUEGO_DISTRIBUIDORA.ID_JUEGO = JUEGO.ID_JUEGO) ON JUEGO.ID_CASADESARROLLADORA = CASA_DESARROLLADORA.ID_CASADESARROLLADORA;");
    }//GEN-LAST:event_BtnEliminarActionPerformed

    private void jTabbedPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane2MouseClicked

    }//GEN-LAST:event_jTabbedPane2MouseClicked

    private void BtnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnActualizarActionPerformed
        actualizar();
    }//GEN-LAST:event_BtnActualizarActionPerformed

    private void TableJuegoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableJuegoMouseClicked
        try {
            mouseClick();
        } catch (SQLException ex) {
            Logger.getLogger(FrameJuegos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_TableJuegoMouseClicked

    private void JRegistroJuegosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JRegistroJuegosMouseClicked
        TableJuego.clearSelection();
        // TableJuego.requestFocusInWindow();
        // TableJuego.getColumnModel().getSelectionModel().clearSelection();

        ListSelectionModel selectionModel = TableJuego.getSelectionModel();
        selectionModel.setAnchorSelectionIndex(-1);
        selectionModel.setLeadSelectionIndex(-1);

        TableColumnModel columnModel = TableJuego.getColumnModel();
        columnModel.getSelectionModel().setAnchorSelectionIndex(-1);
        columnModel.getSelectionModel().setLeadSelectionIndex(-1);
        BtnEliminar.setVisible(false);
        BtnActualizar.setVisible(false);
    }//GEN-LAST:event_JRegistroJuegosMouseClicked

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        enviar();
    }//GEN-LAST:event_AgregarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        Nombre_CasaD.setEditable(true);
        Pais_CasaD.setEditable(true);
        Telefono_CasaD.setEditable(true);
        Nombre_Distribuidor.setEditable(true);
        Pais_Distribuidor.setEditable(true);
        Correo_Distribuidor.setEditable(true);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void CasaComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CasaComboBoxItemStateChanged
        try {
            ResultSet result = casa.Consultar_Casa_Nombre(CasaComboBox.getSelectedItem().toString());
            result.next();
            casa.setId(Integer.parseInt(result.getString(1)));
            Nombre_CasaD.setText(result.getString(2));
            Pais_CasaD.setText(result.getString(3));
            Telefono_CasaD.setText(result.getString(4));

        } catch (SQLException e) {
            if (1 == CasaComboBox.getSelectedIndex()) {
                try {
                    // Iniciamos para la casa
                    id_casadesarrolladora = casa.IncrementoCasa();
                    casa.setId(id_casadesarrolladora);
                    Nombre_CasaD.setText(null);
                    Pais_CasaD.setText(null);
                    Telefono_CasaD.setText(null);

                    Nombre_CasaD.setEditable(true);
                    Pais_CasaD.setEditable(true);
                    Telefono_CasaD.setEditable(true);
                } catch (SQLException ex) {
                    Logger.getLogger(FrameJuegos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_CasaComboBoxItemStateChanged

    private void DistribuidoraComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_DistribuidoraComboBoxItemStateChanged
        try {
            ResultSet result = distribuidor.Consultar_Distribuidor_Nombre(DistribuidoraComboBox.getSelectedItem().toString());
            result.next();
            distribuidor.setId_distribuidor(Integer.parseInt(result.getString(1)));
            Nombre_Distribuidor.setText(result.getString(2));
            Pais_Distribuidor.setText(result.getString(3));
            Correo_Distribuidor.setText(result.getString(4));
        } catch (SQLException e) {
            if (DistribuidoraComboBox.getSelectedIndex() == 1) {

                try {
                    // iniciamos para distribuidor
                    id_distribuidor = distribuidor.Incrementodistribuidor();
                    distribuidor.setId_distribuidor(id_distribuidor);
                    System.out.println("El id con el item agregar de distribuidor: " + id_distribuidor);
                    Nombre_Distribuidor.setText(null);
                    Pais_Distribuidor.setText(null);
                    Correo_Distribuidor.setText(null);

                    Nombre_Distribuidor.setEditable(true);
                    Pais_Distribuidor.setEditable(true);
                    Correo_Distribuidor.setEditable(true);
                } catch (SQLException ex) {
                    Logger.getLogger(FrameJuegos.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        }
    }//GEN-LAST:event_DistribuidoraComboBoxItemStateChanged

    private void VjComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_VjComboBoxItemStateChanged
        try {
            if (VjComboBox.getSelectedIndex() != 0) {
                ResultSet rs = juego.Consultar_VideoJuegos_Nombre((String) VjComboBox.getSelectedItem());
                rs.next();
                int id = Integer.parseInt(rs.getString("id_juego"));

                // Validar si el ID ya existe en la lista
                boolean idExistente = detallesSeleccionados.stream().anyMatch(detalle -> detalle.getId() == id);
                if (idExistente) {
                    return;
                }

                detalle = new Detalle(id, rs.getString("titulo"), Double.parseDouble(rs.getString("precio")), 1);
                detallesSeleccionados.add(detalle);

                sumaSubtotal(InputTotal);
                mostrarT(jTableVideo);
            }
            // Resto del código que deseas ejecutar
        } catch (SQLException ex) {
            Logger.getLogger(FrameJuegos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_VjComboBoxItemStateChanged

    private void mostrarT(JTable tabla) {

        modeloTabla = new DefaultTableModel();
        modeloTabla.addColumn("ID");
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Precio");
        modeloTabla.addColumn("Cantidad");
        modeloTabla.addColumn("Sub-Total");

        for (Detalle detalle : detallesSeleccionados) {
            Object[] fila = {detalle.getId(), detalle.getNombre(), detalle.getPrecio(), detalle.getCantidad(), detalle.getSubtotal()};
            modeloTabla.addRow(fila);
        }

        tabla.setModel(modeloTabla);
    }

    private void jTableVideoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableVideoMouseClicked
        int fila = jTableVideo.getSelectedRow();
        int col = jTableVideo.getSelectedColumn();
        InputCantidad.setText(jTableVideo.getModel().getValueAt(fila, 3).toString());
        idprod = Integer.parseInt(jTableVideo.getModel().getValueAt(fila, 0).toString());
    }//GEN-LAST:event_jTableVideoMouseClicked

    private void actualizarCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarCantidadActionPerformed
        // Obtener el índice del elemento con el ID deseado
        int indice = IntStream.range(0, detallesSeleccionados.size())
                .filter(i -> detallesSeleccionados.get(i).getId() == idprod)
                .findFirst()
                .orElse(-1);

        // Verificar si el índice es válido
        if (indice >= 0) {
            // Acceder al elemento y modificar la cantidad
            Detalle detalleExistente = detallesSeleccionados.get(indice);
            detalleExistente.setCantidad(Integer.parseInt(InputCantidad.getText()));
            detalleExistente.setSubtotal(detalleExistente.getPrecio() * detalleExistente.getCantidad());
            sumaSubtotal(InputTotal);
            idprod = 0;
            InputCantidad.setText(null);
            mostrarT(jTableVideo);
        }

    }//GEN-LAST:event_actualizarCantidadActionPerformed

    private void sumaSubtotal(JTextField dato) {
        dato.setText(detallesSeleccionados.stream()
                .mapToDouble(Detalle::getSubtotal)
                .sum() + "");
    }

    private void EliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarProductoActionPerformed
        // Obtener el índice del elemento con el ID deseado
        int indice = IntStream.range(0, detallesSeleccionados.size())
                .filter(i -> detallesSeleccionados.get(i).getId() == idprod)
                .findFirst()
                .orElse(-1);

        // Verificar si el índice es válido
        if (indice >= 0) {
            // Eliminar el objeto del ArrayList
            detallesSeleccionados.remove(indice);
            sumaSubtotal(InputTotal);
            mostrarT(jTableVideo);
            idprod = 0;
            InputCantidad.setText(null);
        }

    }//GEN-LAST:event_EliminarProductoActionPerformed

    private void GuarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuarVentaActionPerformed
        if (!Cedula.getText().isBlank()
                && !Nombre_CL.getText().isBlank()
                && !Apellido_CL.getText().isBlank()
                && !Telefono.getText().isBlank()
                && !Direccion.getText().isBlank()
                && !Correo_CL.getText().isBlank()) {

            try {
                cliente.setCedula(Integer.parseInt(Cedula.getText()));
                cliente.setNombre(Nombre_CL.getText());
                cliente.setApellido(Apellido_CL.getText());
                cliente.setTelefono(Telefono.getText());
                cliente.setDireccion(Direccion.getText());
                cliente.setCorreo(Correo_CL.getText());
                cliente.InsertarCliente();
            } catch (SQLException ex) {
            }
            try {
                id_venta = venta.IncrementoVenta();
                venta.setId_Venta(id_venta);
                venta.setCliente_CL(cliente.getCedula());
                String fecha = ((JTextField) FechaVenta.getDateEditor().getUiComponent()).getText();
                venta.setFecha(Date.valueOf(fecha));
                venta.setTotal(Double.valueOf(InputTotal.getText()));
                venta.InsertarVenta();
                Rellenar_DetVenta();
            } catch (SQLException ex) {
                Logger.getLogger(FrameJuegos.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Ingrese la informacion del cliente");
        }
    }//GEN-LAST:event_GuarVentaActionPerformed

    private void Rellenar_DetVenta() throws SQLException {
        for (Detalle detalle : detallesSeleccionados) {
            detVenta.setId_VentaD(detVenta.IncrementoDetalle());
            System.out.println("El id incrementado es: " + detVenta.getId_VentaD());
            detVenta.setId_Venta(id_venta);
            detVenta.setId_Juego(detalle.getId());
            detVenta.setCantidad(detalle.getCantidad());
            detVenta.setSubtotal(detalle.getSubtotal());
            detVenta.InsertarDetVenta();
        }
    }

    //Mis metodos Aquí
    private void nuevo() {
        desbloquearTextfields();
        try {

            // iniciamos para el juego
            id_juego = juego.IncrementoJuego();
            txtTitulo.setText(null);
            txtGenero.setText(null);
            txtPrecio.setText(null);
            txtStock.setText(null);

            // iniciamos para juego_distribuidor
            id_juegodistribuidor = juegoDist.Incrementojuegodistribuidor();
            dateLanzamiento.setDate(null);

        } catch (Exception e) {
        }
    }

    private void Rellenar_Casa(JComboBox combo) {
        try {
            ResultSet result;
            result = casa.Consultar_Casa();
            while (result.next()) {
                combo.addItem(result.getString("nombre"));
            }
        } catch (SQLException e) {
            System.out.println("Error con el combo editorial... " + e.getMessage());
        }
    }

    private void Rellenar_Distribuidor(JComboBox combo) {
        try {
            ResultSet result;
            result = distribuidor.Consultar_Distribuidor();
            while (result.next()) {
                combo.addItem(result.getString("nombre"));
            }
        } catch (SQLException e) {
            System.out.println("Error con el combo editorial... " + e.getMessage());
        }
    }

    private void enviar() {
        try {
            // Asignamos a Casa Desarrolladora
            if (CasaComboBox.getSelectedIndex() == 1) {
                System.out.println("El id a get de casa: " + casa.getId());
                casa.setNombre(Nombre_CasaD.getText());
                casa.setPais(Pais_CasaD.getText());
                casa.setTelefono(Telefono_CasaD.getText());
                casa.InsertarCasaDesarrolladora();
            } else {
                System.out.println("El nombre de la casa es : " + CasaComboBox.getSelectedItem().toString());
                ResultSet rs = casa.Consultar_Casa_Nombre(CasaComboBox.getSelectedItem().toString());
                rs.next();
                id_casadesarrolladora = Integer.parseInt(rs.getString(1));
            }

            // Asignamos a Juego
            juego.setId(id_juego);
            juego.setCasaD(id_casadesarrolladora);
            juego.setTitulo(txtTitulo.getText());
            juego.setGenero(txtGenero.getText());
            juego.setPrecio(Float.parseFloat(txtPrecio.getText()));
            juego.setStock(Integer.parseInt(txtStock.getText()));
            juego.InsertarJuego();

            // Asignamos a Distribuidora
            if (1 == DistribuidoraComboBox.getSelectedIndex()) {
                System.out.println("El id del distribuidor get: " + distribuidor.getId_distribuidor());
                distribuidor.setNombre(Nombre_Distribuidor.getText());
                distribuidor.setPais(Pais_Distribuidor.getText());
                distribuidor.setCorreo(Correo_Distribuidor.getText());
                distribuidor.InsertarDistribuidora();
            } else {
                System.out.println("El nombre de la casa es : " + DistribuidoraComboBox.getSelectedItem().toString());
                ResultSet rs = distribuidor.Consultar_Distribuidor_Nombre(DistribuidoraComboBox.getSelectedItem().toString());
                rs.next();
                id_distribuidor = Integer.parseInt(rs.getString(1));
            }

            // Asignamos a Juego_Distribuidor
            juegoDist.setId_Juego_Distr(id_juegodistribuidor);
            juegoDist.setId_Juego(id_juego);
            juegoDist.setId_Distribuidor(id_distribuidor);

            String fecha = ((JTextField) dateLanzamiento.getDateEditor().getUiComponent()).getText();
            juegoDist.setPublicacion(Date.valueOf(fecha));
            juegoDist.InsertarDistribuidora();

            nuevo();
            mostrar(TableJuego, "SELECT JUEGO.ID_JUEGO AS ID, JUEGO.TITULO AS NOMBRE, JUEGO.GENERO, JUEGO.PRECIO, JUEGO.STOCK, CASA_DESARROLLADORA.NOMBRE AS DESARROLLADORA, JUEGO_DISTRIBUIDORA.PUBLICACION, DISTRIBUIDORA.NOMBRE AS DISTRIBUIDORA\n"
                    + "FROM CASA_DESARROLLADORA INNER JOIN (JUEGO INNER JOIN (JUEGO_DISTRIBUIDORA INNER JOIN DISTRIBUIDORA ON DISTRIBUIDORA.ID_DISTRIBUIDORA = JUEGO_DISTRIBUIDORA.ID_DISTRIBUIDORA)\n"
                    + "ON JUEGO_DISTRIBUIDORA.ID_JUEGO = JUEGO.ID_JUEGO) ON JUEGO.ID_CASADESARROLLADORA = CASA_DESARROLLADORA.ID_CASADESARROLLADORA;");
            JOptionPane.showMessageDialog(null, "Dato ingresado con exito!");
        } catch (Exception e) {
        }
    }

    private void MisMetodos() {
        try {
            bloquearTextfields();
        } catch (Exception e) {
        }
        FocusListener focusListener = new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                obtenerCampo = (JTextField) e.getSource();
            }

            @Override
            public void focusLost(FocusEvent e) {

            }
        };

        txtTitulo.addFocusListener(focusListener);
        txtGenero.addFocusListener(focusListener);
        dateLanzamiento.addFocusListener(focusListener);
        txtPrecio.addFocusListener(focusListener);
        txtStock.addFocusListener(focusListener);

        BtnEliminar.setVisible(false);
        BtnActualizar.setVisible(false);

    }

    private void mostrar(javax.swing.JTable T, String Sql) {
        try {
            ResultSet rs;
            DefaultTableModel m = new DefaultTableModel();
            T.setModel(m);
            rs = juego.consultaTabla(Sql);
            ResultSetMetaData rsMd;
            rsMd = rs.getMetaData();
            int cantColumnas = rsMd.getColumnCount();
            for (int i = 1; i <= cantColumnas; i++) {
                m.addColumn(rsMd.getColumnLabel(i));
            }
            while (rs.next()) {
                Object[] col = new Object[cantColumnas];
                for (int i = 0; i < cantColumnas; i++) {
                    col[i] = rs.getObject(i + 1);
                }
                m.addRow(col);
            }
        } catch (Exception e) {
        }
    }

    private void eliminaRegistro() {
        int opcion = JOptionPane.showConfirmDialog(null, "¿Desea eliminar este registro?", "WARNING", JOptionPane.YES_NO_OPTION, 2);

        if (opcion == JOptionPane.YES_OPTION) {
            try {
                DefaultTableModel tm = (DefaultTableModel) TableJuego.getModel();
                String ID = String.valueOf(tm.getValueAt(TableJuego.getSelectedRow(), 0));
                juego.setId(Integer.parseInt(ID));
                juegoDist.setId_Juego_Distr(id_juegodistribuidor);
                juegoDist.eliminarJuegoDistribuidor();
                juego.EliminarJuego();
            } catch (Exception e) {
            }
            BtnEliminar.setEnabled(false);
        } else {
            BtnEliminar.setEnabled(false);
        }
    }

    private void actualizar() {
        try {
            // Asignamos a Casa Desarrolladora
            casa.setId(id_casadesarrolladora);
            casa.setNombre(Nombre_CasaD.getText());
            casa.setPais(Pais_CasaD.getText());
            casa.setTelefono(Telefono_CasaD.getText());
            casa.ActualizarCasaDesarrolladora();

            // Asignamos a Juego
            juego.setId(id_juego);
            juego.setCasaD(id_casadesarrolladora);
            juego.setTitulo(txtTitulo.getText());
            juego.setGenero(txtGenero.getText());
            juego.setPrecio(Float.parseFloat(txtPrecio.getText()));
            juego.setStock(Integer.parseInt(txtStock.getText()));
            juego.ActualizarJuego();

            // Asignamos a Distribuidora
            distribuidor.setId_distribuidor(id_distribuidor);
            distribuidor.setNombre(Nombre_Distribuidor.getText());
            distribuidor.setPais(Pais_Distribuidor.getText());
            distribuidor.setCorreo(Correo_Distribuidor.getText());
            distribuidor.ActualizarDistribuidor();

            // Asignamos a Juego_Distribuidor
            juegoDist.setId_Distribuidor(id_juegodistribuidor);
            juegoDist.setId_Juego(id_juego);
            juegoDist.setId_Distribuidor(id_distribuidor);

            String fecha = ((JTextField) dateLanzamiento.getDateEditor().getUiComponent()).getText();
            juegoDist.setPublicacion(Date.valueOf(fecha));
            juegoDist.ActualizarJuegoDistribuidor();
            nuevo();
            mostrar(TableJuego, "SELECT JUEGO.ID_JUEGO AS ID, JUEGO.TITULO AS NOMBRE, JUEGO.GENERO, JUEGO.PRECIO, JUEGO.STOCK, CASA_DESARROLLADORA.NOMBRE AS DESARROLLADORA, JUEGO_DISTRIBUIDORA.PUBLICACION, DISTRIBUIDORA.NOMBRE AS DISTRIBUIDORA\n"
                    + "FROM CASA_DESARROLLADORA INNER JOIN (JUEGO INNER JOIN (JUEGO_DISTRIBUIDORA INNER JOIN DISTRIBUIDORA ON DISTRIBUIDORA.ID_DISTRIBUIDORA = JUEGO_DISTRIBUIDORA.ID_DISTRIBUIDORA)\n"
                    + "ON JUEGO_DISTRIBUIDORA.ID_JUEGO = JUEGO.ID_JUEGO) ON JUEGO.ID_CASADESARROLLADORA = CASA_DESARROLLADORA.ID_CASADESARROLLADORA;");
            JOptionPane.showMessageDialog(null, "Dato actualizado con exito!");

        } catch (Exception e) {
        }
    }

    private void mouseClick() throws SQLException {
        int fila = TableJuego.getSelectedRow();
        int col = TableJuego.getSelectedColumn();

        juego.setId(Integer.parseInt(TableJuego.getModel().getValueAt(fila, 0).toString()));
        casa.setNombre(TableJuego.getModel().getValueAt(fila, 5).toString());
        juegoDist.setId_Juego(juego.getId());
        distribuidor.setNombre(TableJuego.getModel().getValueAt(fila, 7).toString());
        this.CamposRelleno();
        BtnEliminar.setVisible(true);
        BtnActualizar.setVisible(true);
    }

    private void CamposRelleno() throws SQLException {
        ResultSet resultjuego = juego.Consultar_Juego_ID();
        ResultSet resultCasa = casa.Consultar_Casa();
        ResultSet resultdistribuidora = distribuidor.Consultar_Distribuidor();
        // Rellenamos para El juego
        resultjuego.next();
        juego.setId(Integer.parseInt(resultjuego.getString(1)));
        id_juego = juego.getId();
        txtTitulo.setText(resultjuego.getString(3));
        txtGenero.setText(resultjuego.getString(4));
        txtStock.setText(resultjuego.getString(6));
        txtPrecio.setText(resultjuego.getString(5));
        //ResultSet resultJuegoDist = juegoDist;

        // Rellenar para Distribuidor
        resultdistribuidora.next();
        distribuidor.setId_distribuidor(Integer.parseInt(resultdistribuidora.getString(1)));
        id_distribuidor = distribuidor.getId_distribuidor();
        Nombre_Distribuidor.setText(resultdistribuidora.getString(2));
        Pais_Distribuidor.setText(resultdistribuidora.getString(3));
        Correo_Distribuidor.setText(resultdistribuidora.getString(4));

        // Rellenar para Casa
        resultCasa.next();
        casa.setId(Integer.parseInt(resultCasa.getString(1)));
        id_casadesarrolladora = casa.getId();
        Nombre_CasaD.setText(resultCasa.getString(2));
        Pais_CasaD.setText(resultCasa.getString(3));
        Telefono_CasaD.setText(resultCasa.getString(4));

        //Rellenar para Juego_Distribuidor
        juegoDist.setId_Distribuidor(distribuidor.getId_distribuidor());
        ResultSet resultJuegoDistr = juegoDist.Consultar_Juego_Distribuidor();
        resultJuegoDistr.next();
        juegoDist.setId_Juego_Distr(Integer.parseInt(resultJuegoDistr.getString(1)));
        id_juegodistribuidor = juegoDist.getId_Juego_Distr();
        dateLanzamiento.setDate(Date.valueOf(resultJuegoDistr.getString(4)));
        desbloquear();
    }

    private void bloquearTextfields() {
        txtTitulo.setEditable(false);
        txtGenero.setEditable(false);
        dateLanzamiento.setEnabled(false);
        txtPrecio.setEditable(false);
        txtStock.setEditable(false);
        Nombre_CasaD.setEditable(false);
        Pais_CasaD.setEditable(false);
        Telefono_CasaD.setEditable(false);
        Nombre_Distribuidor.setEditable(false);
        Pais_Distribuidor.setEditable(false);
        Correo_Distribuidor.setEditable(false);
    }

    private void desbloquearTextfields() {
        txtTitulo.setEditable(true);
        txtGenero.setEditable(true);
        dateLanzamiento.setEnabled(true);
        txtPrecio.setEditable(true);
        txtStock.setEditable(true);
    }

    private void desbloquear() {
        txtTitulo.setEditable(true);
        txtGenero.setEditable(true);
        dateLanzamiento.setEnabled(true);
        txtPrecio.setEditable(true);
        txtStock.setEditable(true);
    }

    private void Rellenar_videoJuegos(JComboBox combo) {
        try {
            ResultSet result;
            result = juego.Consultar_VideoJuego();
            while (result.next()) {
                combo.addItem(result.getString("titulo"));
            }
        } catch (SQLException e) {
            System.out.println("Error con el combo editorial... " + e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JTextField Apellido_CL;
    private javax.swing.JButton BtnActualizar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnNuevo;
    private javax.swing.JButton BuscarCL;
    private javax.swing.JComboBox<String> CasaComboBox;
    private javax.swing.JTextField Cedula;
    private javax.swing.JTextField Correo_CL;
    private javax.swing.JTextField Correo_Distribuidor;
    private javax.swing.JTextField Direccion;
    private javax.swing.JComboBox<String> DistribuidoraComboBox;
    private javax.swing.JButton EliminarProducto;
    private com.toedter.calendar.JDateChooser FechaVenta;
    private javax.swing.JButton GuarVenta;
    private javax.swing.JTextField InputBuscarCL;
    private javax.swing.JTextField InputCantidad;
    private javax.swing.JTextField InputTotal;
    private javax.swing.JPanel JPanelPadre;
    private javax.swing.JPanel JRegistroJuegos;
    private javax.swing.JTextField Nombre_CL;
    private javax.swing.JTextField Nombre_CasaD;
    private javax.swing.JTextField Nombre_Distribuidor;
    private javax.swing.JTextField Pais_CasaD;
    private javax.swing.JTextField Pais_Distribuidor;
    private javax.swing.JSeparator SeparadorJuego;
    private javax.swing.JTable TableJuego;
    private javax.swing.JTextField Telefono;
    private javax.swing.JTextField Telefono_CasaD;
    private javax.swing.JButton VaciarVenta;
    private javax.swing.JComboBox<String> VjComboBox;
    private javax.swing.JButton actualizarCantidad;
    private javax.swing.JButton btnEditar;
    private com.toedter.calendar.JDateChooser dateLanzamiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jRegistroVenta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTableVideo;
    private javax.swing.JTextField txtGenero;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JSeparator videojuegoSeparador;
    private javax.swing.JSeparator videojuegoSeparador1;
    private javax.swing.JSeparator videojuegoSeparador2;
    private javax.swing.JSeparator videojuegoSeparador3;
    // End of variables declaration//GEN-END:variables

}
